### ISSUE TITLE
HTTPS for quake2download

### ISSUE THREAD

**Issue by Fryziu** [quake2download/quake2download#1]
In one browser I'm getting a warning about an unsafe connection, and in another an error in WordPress.
Please fix it, I'm trying to make a YouTube movie about Q2 and I can't recommend a web page that scares potential gamers with warnings and errors.
![quake2download pl](https://github.com/quake2download/quake2download/assets/24547047/ccd402e4-44f8-4f49-8b6d-e9088f3c7db0)

**Comment by exanrauzer** [comment]
4bid renewed the https certificate.

Should be fine now.
